[package]
name = "appentry-derive"
version = "0.1.4"
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/fawdlstty/appentry"
homepage = "https://github.com/fawdlstty/appentry"
description = "A minimalist command-line argument parsing library"
authors = ["fawdlstty<f@fawdlstty.com>"]
keywords = ["shell", "parse"]
categories = []
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
inventory = "0.3.21"
proc-macro2 = "1.0.105"
quote = "1.0.43"
syn = { version = "2.0.114", features = ["full"] }
