[package]
name = "appentry"
version = "0.1.2"
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/fawdlstty/appentry"
homepage = "https://github.com/fawdlstty/appentry"
description = "A minimalist command-line argument parsing library"
authors = ["fawdlstty<f@fawdlstty.com>"]
keywords = ["shell", "parse"]
categories = []
readme = "../README.md"
exclude = ["src/main.rs"]

[dependencies]
anyhow = "1.0.100"
appentry-derive = { version = "0.1.2", path = "../appentry-derive" }
inventory = "0.3.21"

# cargo publish -p appentry-derive --allow-dirty --registry crates-io
# cargo publish -p appentry --allow-dirty --registry crates-io
